// Generated by scripts/export_public_dashboard.py from measured VALID artifacts.
// Do not edit scores by hand or present this snapshot as live inference.
export default {
  "available": true,
  "base_sha": "051ce64a7cf0ab999f8aacb81fa405d5fa0257cf",
  "comparison_group": "v3-valid-b876f9424b049eee",
  "cutoff": "2026-01-01",
  "ensemble_weights": {
    "catboost": 0.75,
    "recurrence_heuristic": 0.25
  },
  "evaluation_sha": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
  "evidence_sources": {
    "v4": {
      "commit": "135a50810e0e34ede2a0dd6b2e05dfb5d3551c29",
      "git_blob": "2aa881b3f8096c805457c1ace14cbfa098c9f8ae",
      "narrative_path": "reports/v4_synthesis.md",
      "path": "reports/v4_final_decision.json",
      "ref": "integration/v4-synthesis"
    },
    "versions": {
      "git_blob": "da6a14603255bf6f616efc25c6cad020f194b6e7",
      "path": "reports/v2_final_report.md",
      "valid_fingerprints": {
        "data/raw/ubs_2026/valid_labels.csv": "979bd9b69253084fc9e2b1ef473c07a628a8b18091169051ba304cfed0fb5642",
        "data/raw/ubs_2026/valid_transactions.jsonl": "2c30941d49ca20f7b082526407f24529c5a704205610373eff952f4f444a3622"
      }
    }
  },
  "experiments": [
    {
      "candidate": "V2",
      "delta_vs_baseline": 0.0,
      "experiment_id": "v3-valid-b876f9424b049eee-V2",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.424,
        "macro_f1": 0.3915494559105542,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "History and periodicity",
      "model_name": "V2 baseline",
      "model_version": "V2",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 1,
      "source": "valid_results.json"
    },
    {
      "candidate": "history_control",
      "delta_vs_baseline": -0.007598967894151876,
      "experiment_id": "v3-valid-b876f9424b049eee-history_control",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.424,
        "macro_f1": 0.3839504880164023,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "History-feature control",
      "model_name": "History only",
      "model_version": "history_control",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 2,
      "source": "valid_results.json"
    },
    {
      "candidate": "A",
      "delta_vs_baseline": 0.032561641825957444,
      "experiment_id": "v3-valid-b876f9424b049eee-A",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.461,
        "macro_f1": 0.4241110977365116,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "Cross-fitted family identity features",
      "model_name": "V3-A \u00b7 family identity",
      "model_version": "V3-A",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "selected",
      "sequence": 3,
      "source": "valid_results.json"
    },
    {
      "candidate": "B",
      "delta_vs_baseline": -0.0024344465468912335,
      "experiment_id": "v3-valid-b876f9424b049eee-B",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.423,
        "macro_f1": 0.38911500936366294,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "Additional periodicity features",
      "model_name": "V3-B \u00b7 recurrence",
      "model_version": "B",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 4,
      "source": "valid_results.json"
    },
    {
      "candidate": "full",
      "delta_vs_baseline": 0.006944757556017589,
      "experiment_id": "v3-valid-b876f9424b049eee-full",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.448,
        "macro_f1": 0.39849421346657177,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "Identity and periodicity",
      "model_name": "V3 full",
      "model_version": "full",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 5,
      "source": "valid_results.json"
    },
    {
      "candidate": "ensemble",
      "delta_vs_baseline": 0.03835170382855785,
      "experiment_id": "v3-valid-b876f9424b049eee-ensemble",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.47,
        "macro_f1": 0.429901159739112,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "Fixed 50/50 blend",
      "model_name": "V3 / V2 blend",
      "model_version": "ensemble",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 6,
      "source": "valid_results.json"
    },
    {
      "candidate": "focused",
      "delta_vs_baseline": 0.021365903981549528,
      "experiment_id": "v3-valid-b876f9424b049eee-focused",
      "git_commit": "5884ddd07a19b2e19b44b4fd55afdf4eb6dcf749",
      "metrics": {
        "accuracy": 0.431,
        "macro_f1": 0.4129153598921037,
        "run_id": "v3-valid-b876f9424b049eee",
        "scope": "validation",
        "validation_clients": 1000
      },
      "milestone": "Fixed 0.85 threshold; no VALID search",
      "model_name": "Focused correction",
      "model_version": "focused",
      "notes": "Historical comparison on reused VALID; source-report order, not chronology.",
      "order_kind": "report",
      "recorded_at_utc": null,
      "result": "evaluated",
      "sequence": 7,
      "source": "valid_results.json"
    }
  ],
  "horizon_days": 90,
  "importance": [
    {
      "feature": "mcc_4814_share",
      "importance": 4.618782089975526
    },
    {
      "feature": "mcc_5734_share",
      "importance": 4.318385412882582
    },
    {
      "feature": "identity_streaming_aliases",
      "importance": 4.208519156065398
    },
    {
      "feature": "mcc_4814_count",
      "importance": 4.201109525044166
    },
    {
      "feature": "identity_cloud_share",
      "importance": 4.165171968741796
    },
    {
      "feature": "mcc_5734_count",
      "importance": 3.588680884244513
    },
    {
      "feature": "identity_music_share",
      "importance": 3.5660171262716367
    },
    {
      "feature": "identity_insurance_aliases",
      "importance": 3.176323922702333
    },
    {
      "feature": "mcc_7997_count",
      "importance": 3.0801988811526795
    },
    {
      "feature": "mcc_6300_count",
      "importance": 2.593837360190888
    },
    {
      "feature": "identity_music_aliases",
      "importance": 2.5556534494332044
    },
    {
      "feature": "mcc_5812_share",
      "importance": 2.510022874434912
    }
  ],
  "importance_method": "CatBoost PredictionValuesChange",
  "importance_scope": "CatBoost arm A, fitted on TRAIN for VALID evaluation",
  "metrics": {
    "accuracy": 0.461,
    "baseline_macro_f1": 0.3915494559105542,
    "delta_vs_baseline": 0.032561641825957444,
    "macro_f1": 0.4241110977365116,
    "macro_recall": 0.42680105297353066,
    "validation_clients": 1000
  },
  "model_version": "V3-A",
  "publication_mode": "read_only_aggregate_snapshot",
  "report_sha256": "b876f9424b049eee813d978361674823bd86a6b50e663ade1dfca176c2eeeac9",
  "scope": "validation",
  "v4_diagnostics": [
    {
      "branch": "exp/v4-shift-corruption-ginestar",
      "evidence": "verified",
      "id": "ginestar-severe",
      "macro_f1": 0.3733838220578183,
      "name": "Identity-corruption stress test",
      "note": "V3-A under simulated corruption, not a replacement model.",
      "protocol": "stress-not-comparable-to-clean",
      "scope": "TRAIN OOF \u00b7 synthetic severe corruption"
    }
  ],
  "v4_experiments": [
    {
      "branch": "baseline/v4-frozen",
      "id": "v3a",
      "name": "Frozen V3-A",
      "note": "Retained for transfer reliability; not the highest TRAIN OOF score.",
      "status": "selected",
      "train_evidence": "verified",
      "train_oof": 0.45979382686863396,
      "valid": 0.4241110977365116,
      "valid_evidence": "verified; VALID reused"
    },
    {
      "branch": "exp/v4-direct-robust-javi",
      "id": "javi-direct",
      "name": "Direct robust classifier",
      "note": "Large transfer failure on reused VALID.",
      "status": "evaluated",
      "train_evidence": "verified",
      "train_oof": 0.507419936954947,
      "valid": 0.076353284,
      "valid_evidence": "author-reported; VALID reused"
    },
    {
      "branch": "exp/v4-merchant-intelligence-christian",
      "id": "christian-b",
      "name": "Merchant intelligence B",
      "note": "Full expensive graph/model run was not independently repeated.",
      "status": "evaluated",
      "train_evidence": "author-reported; transductive unsupervised component",
      "train_oof": 0.482502095,
      "valid": 0.337777577,
      "valid_evidence": "author-reported; VALID reused"
    },
    {
      "branch": "exp/v4-soft-candidate-santiago",
      "id": "santiago-ranker",
      "name": "Soft candidate ranker",
      "note": "Strongest TRAIN candidate, but below V3-A on reused VALID.",
      "status": "evaluated",
      "train_evidence": "verified",
      "train_oof": 0.5426622087569586,
      "valid": 0.4006622046362836,
      "valid_evidence": "verified; VALID reused"
    },
    {
      "branch": "exp/v4-soft-candidate-santiago",
      "id": "santiago-logistic",
      "name": "Soft candidate logistic",
      "note": "No recorded VALID evaluation.",
      "status": "evaluated",
      "train_evidence": "verified",
      "train_oof": 0.4991810426021103,
      "valid": null,
      "valid_evidence": "not evaluated"
    },
    {
      "branch": "integration/v4-synthesis",
      "id": "santiago-average",
      "name": "Fixed 50/50 A + ranker average",
      "note": "Predeclared weights; not tuned or tested on VALID.",
      "status": "evaluated",
      "train_evidence": "verified",
      "train_oof": 0.5400597679950233,
      "valid": null,
      "valid_evidence": "not evaluated",
      "weights": {
        "ranker": 0.5,
        "v3a": 0.5
      }
    },
    {
      "branch": "exp/v4-survival-laura",
      "id": "laura-hybrid",
      "name": "Temporal hybrid \u00b7 median gap",
      "note": "Official target, distinct temporal research arm.",
      "status": "evaluated",
      "train_evidence": "verified",
      "train_oof": 0.4572161680832407,
      "valid": 0.3891,
      "valid_evidence": "author-reported; VALID reused"
    },
    {
      "branch": "exp/v4-self-supervised-esteban",
      "id": "esteban-svd",
      "name": "SVD + history statistics",
      "note": "Unsupervised representation is transductive; not an inductive-client claim.",
      "status": "evaluated",
      "train_evidence": "verified; transductive unsupervised component",
      "train_oof": 0.4391003104865256,
      "valid": 0.3219,
      "valid_evidence": "author-reported; VALID reused"
    }
  ],
  "validation_independent": false,
  "version_history": [
    {
      "clients": 1000,
      "evidence": "reported and reproduced",
      "id": "v1",
      "is_subversion": false,
      "kind": "measured",
      "label": "V1 baseline",
      "macro_f1": 0.2710242658492452,
      "protocol": "official-eight-class-valid-1000",
      "scope": "VALID",
      "source": "reports/v2_final_report.md#v1-baseline",
      "version": "V1"
    },
    {
      "clients": 1000,
      "evidence": "reported and reproduced",
      "id": "v2",
      "is_subversion": false,
      "kind": "measured",
      "label": "V2 final",
      "macro_f1": 0.391549456,
      "protocol": "official-eight-class-valid-1000",
      "scope": "VALID",
      "source": "reports/v2_final_report.md#candidates-evaluated",
      "version": "V2"
    },
    {
      "clients": 1000,
      "evidence": "measured; reused VALID",
      "id": "v3-a",
      "is_subversion": true,
      "kind": "measured",
      "label": "V3-A",
      "macro_f1": 0.4241110977365116,
      "protocol": "official-eight-class-valid-1000",
      "report_sha256": "b876f9424b049eee813d978361674823bd86a6b50e663ade1dfca176c2eeeac9",
      "scope": "VALID",
      "selected": true,
      "source": "outputs/metrics/ubs_v3/valid_results.json#A",
      "version": "V3"
    },
    {
      "clients": 1000,
      "evidence": "measured; reused VALID",
      "id": "v3-b",
      "is_subversion": true,
      "kind": "measured",
      "label": "V3-B",
      "macro_f1": 0.38911500936366294,
      "protocol": "official-eight-class-valid-1000",
      "report_sha256": "b876f9424b049eee813d978361674823bd86a6b50e663ade1dfca176c2eeeac9",
      "scope": "VALID",
      "selected": false,
      "source": "outputs/metrics/ubs_v3/valid_results.json#B",
      "version": "V3"
    },
    {
      "clients": 1000,
      "evidence": "measured; reused VALID",
      "id": "v3-full",
      "is_subversion": true,
      "kind": "measured",
      "label": "V3 full",
      "macro_f1": 0.39849421346657177,
      "protocol": "official-eight-class-valid-1000",
      "report_sha256": "b876f9424b049eee813d978361674823bd86a6b50e663ade1dfca176c2eeeac9",
      "scope": "VALID",
      "selected": false,
      "source": "outputs/metrics/ubs_v3/valid_results.json#full",
      "version": "V3"
    },
    {
      "clients": 1000,
      "evidence": "measured; reused VALID",
      "id": "v3-ensemble",
      "is_subversion": true,
      "kind": "measured",
      "label": "V3/V2 blend",
      "macro_f1": 0.429901159739112,
      "protocol": "official-eight-class-valid-1000",
      "report_sha256": "b876f9424b049eee813d978361674823bd86a6b50e663ade1dfca176c2eeeac9",
      "scope": "VALID",
      "selected": false,
      "source": "outputs/metrics/ubs_v3/valid_results.json#ensemble",
      "version": "V3"
    },
    {
      "base_sha": "051ce64a7cf0ab999f8aacb81fa405d5fa0257cf",
      "id": "v4",
      "is_subversion": false,
      "kind": "decision",
      "label": "V4 decision",
      "macro_f1": null,
      "note": "V3-A retained; V4 did not promote a new predictor or claim a gain.",
      "scope": "No new VALID evaluation",
      "selected_model": "V3-A",
      "source": "reports/v4_synthesis.md#final-model-decision",
      "version": "V4"
    }
  ]
};
