"""Export a safe aggregate snapshot for the public Vercel dashboard.

The source remains the frozen V3 VALID report. No client rows, transactions,
TEST labels or submission predictions are copied to the public deployment.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from transaction_forecasting.api.dashboard import BASE_SHA, snapshot  # noqa: E402

PUBLIC_FIELDS = (
    "available",
    "model_version",
    "base_sha",
    "horizon_days",
    "cutoff",
    "metrics",
    "importance",
    "experiments",
    "comparison_group",
    "scope",
    "version_history",
    "v4_experiments",
    "v4_diagnostics",
    "evidence_sources",
    "importance_scope",
    "importance_method",
    "validation_independent",
    "evaluation_sha",
    "report_sha256",
    "ensemble_weights",
)
OUTPUT = REPO / "frontend" / "publicSnapshot.js"


def export_content(artifact_root: Path) -> str:
    measured = snapshot(artifact_root.resolve())
    if not measured["available"] or measured["metrics"] is None:
        raise ValueError("The measured V3 VALID artifact is required for public export")
    if measured["base_sha"] != BASE_SHA or measured["model_version"] != "V3-A":
        raise ValueError("The selected frozen predictor does not match V3-A")
    if measured["metrics"]["validation_clients"] != 1000:
        raise ValueError("Expected the recorded 1,000-client VALID cohort")
    if not measured["report_sha256"] or len(measured["report_sha256"]) != 64:
        raise ValueError("The source report digest is unavailable")
    if not measured["experiments"] or not measured["importance"]:
        raise ValueError("The recorded experiments and importance are required")
    public = {key: measured[key] for key in PUBLIC_FIELDS}
    public["publication_mode"] = "read_only_aggregate_snapshot"
    serialized = json.dumps(public, indent=2, sort_keys=True, ensure_ascii=True)
    if any(f'"{key}"' in serialized for key in ("client_id", "transactions", "submission")):
        raise ValueError("Client-level data is not allowed in the public snapshot")
    return (
        "// Generated by scripts/export_public_dashboard.py from measured VALID artifacts.\n"
        "// Do not edit scores by hand or present this snapshot as live inference.\n"
        f"export default {serialized};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact-root", required=True, type=Path)
    parser.add_argument("--check", action="store_true", help="Verify the committed export")
    args = parser.parse_args()
    content = export_content(args.artifact_root)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Public snapshot is stale; re-export from the frozen report")
        print("Public snapshot matches the measured source")
        return
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Exported aggregate evidence to {OUTPUT}")


if __name__ == "__main__":
    main()
