"""Rebuild the frozen Stream Identity submission without reopening VALID labels.

This integration launcher keeps the frozen research runner byte-for-byte intact.
It rebuilds TRAIN features, fits the approved recipe, predicts VALID/TEST without
reading labels, validates the test CSV, and requires an exact match with the
committed clean submission when that reference is present.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import shutil
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WORK_DIR = ROOT / "outputs/stream_identity_reproduction"
DEFAULT_OUTPUT = (
    ROOT / "outputs/predictions/submission_stream_identity_clean_regenerated.csv"
)
DEFAULT_REFERENCE = ROOT / "outputs/predictions/submission_stream_identity_clean.csv"


def _load_frozen_runner():
    path = ROOT / "scripts/run_stream_identity_clean.py"
    spec = importlib.util.spec_from_file_location("frozen_stream_identity_runner", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load frozen runner: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=DEFAULT_WORK_DIR,
        help="Fresh directory for ignored model and prediction artifacts.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Destination for the regenerated, validated CSV.",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=DEFAULT_REFERENCE,
        help="Committed CSV that the regenerated bytes must match.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    work_dir = args.work_dir.resolve()
    output = args.output.resolve()
    reference = args.reference.resolve()
    if work_dir.exists() and any(work_dir.iterdir()):
        raise FileExistsError(f"Work directory must be fresh: {work_dir}")
    if output.exists():
        raise FileExistsError(f"Refusing to overwrite output: {output}")

    runner = _load_frozen_runner()
    runner.OUT = work_dir
    runner.rebuild()
    runner.predict()

    candidate = work_dir / "submission_candidate.csv"
    sample = pd.read_csv(
        runner.RAW / "sample_submission.csv", dtype=str, keep_default_na=False
    )
    predictions = pd.read_csv(candidate, dtype=str, keep_default_na=False)
    normalized = runner.validate_submission(predictions, sample)
    # The approved artifact uses CRLF and is marked -text in .gitattributes.
    # Pin serialization so a Linux reproduction can be compared byte-for-byte.
    normalized.to_csv(candidate, index=False, lineterminator="\r\n")

    if reference.exists() and candidate.read_bytes() != reference.read_bytes():
        raise RuntimeError(
            "Regenerated submission differs from the committed clean reference; "
            "the reference was not overwritten"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(candidate, output)
    print(f"Submission: {output.relative_to(ROOT).as_posix()}")
    print(f"Rows: {len(normalized)}")
    print(f"SHA256: {_sha256(output)}")
    print(
        "Reference match: YES" if reference.exists() else "Reference match: unavailable"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
